ecommerceapp/urls.py
from django.urls import path
from .views import *
# from .views import


app_name = "ecommerceapp"

urlpatterns = [
    path('', ClientHomeView.as_view(), name='clienthome'),
    path('category/<slug:slug>', CategoryDetailView.as_view(), name="categorydetail"),
    path('add-to-cart/<int:pk>/', AddToCartView.as_view(), name="addtocart"),
    path('cart/', CartView.as_view(), name="cart"),
    path('manage-cart/<int:pk>/<action>/',
         ManageCartView.as_view(), name="managecart"),
    path('empty-cart/', EmptyCartView.as_view(), name="emptycart"),
    path('customer/sign-up', CustomerSignupView.as_view(), name="customersignup"),
    path('customer/sign-in', CustomerSigninView.as_view(), name="customersignin"),
    path("customer/sign-out", CustomerSignoutView.as_view(), name="customersignout"),
    path("customer/profile", CustomerProfileView.as_view(), name="customerprofile"),
    path('customer/<int:pk>/profile',
         ProfileDetailView.as_view(), name='profiledetail'),

    path('order/', OrderCreateView.as_view(), name="ordercreate"),




    path('med-admin/home/', AdminHomeView.as_view(), name='adminhome'),
    path('med-admin/cartlist', AdminCartListView.as_view(), name='admincartlist'),

    path("med-admin/cartlist/<int:pk>/detail/",
         AdminCartListDetailView.as_view(), name="admincartlistdetail"),
    path('med-admin/orderlist', AdminOrderListView.as_view(), name='adminorderlist'),
    path("med-admin/orderlist/<int:pk>/detail/",
         AdminOrderListDetailView.as_view(), name="adminorderlistdetail"),

    # admin product category
    path('med-admin/productcategory/create',
         AdminProductCategoryCreateView.as_view(), name='adminproductcategorycreate'),
    path('med-admin/productcategory/list',
         AdminProductCategoryListView.as_view(), name='adminproductcategorylist'),
    path('med-admin/productcategory/<int:pk>/delete',
         AdminProductCategoryDeleteView.as_view(), name='adminproductcategorydelete'),
    path('med-admin/productcategory/<int:pk>/update',
         AdminProductCategoryUpdateView.as_view(), name='adminproductcategoryupdate'),

    # admin product
    path('med-admin/product/create',
         AdminProductCreateView.as_view(), name='adminproductcreate'),
    path('med-admin/product/list',
         AdminProductListView.as_view(), name='adminproductlist'),
    path('med-admin/product/<int:pk>/delete',
         AdminProductDeleteView.as_view(), name='adminproductdelete'),
    path('med-admin/product/<int:pk>/update',
         AdminProductUpdateView.as_view(), name='adminproductupdate'),

    # admin product image
    path('med-admin/productimage/create',
         AdminProductImageCreateView.as_view(), name='adminproductimagecreate'),
    path('med-admin/productimage/list',
         AdminProductImageListView.as_view(), name='adminproductimagelist'),
    path('med-admin/productimage/<int:pk>/delete',
         AdminProductImageDeleteView.as_view(), name='adminproductimagedelete'),
    path('med-admin/productimage/<int:pk>/update',
         AdminProductImageUpdateView.as_view(), name='adminproductimageupdate'),




]

ecommerceproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include('ecommerceapp.urls')),
   
    

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/clienttemplate/addtocart.html
<h3>Product Added to cart sucessfully</h3>

templates/clienttemplate/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title></title>
	
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<style>

.card {
  box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
  transition: 0.3s;
  width: 60%;
}

.card:hover {
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
}

.contain {
  padding: 2px 16px;
}


.overlay {
  position: absolute;
  top: 0;
  bottom: 0;

  height: 20%;
  width: 89%;
  opacity: 0;
  padding: 30px 0px 10px;

  transition: .5s all;
  background-color:rgba(0, 0, 0, 0.8);
 
}

.col-md-3:hover .overlay {
  opacity: 2;
}

.text {
  color: white;
  font-size: 20px;
  position: absolute;
  top: 50%;
  left: 50%;
  -webkit-transform: translate(-50%, -50%);
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
  text-align: center;
}
</style>
<body class="container-fluid">


	

	
  <nav class="navbar navbar-expand-lg navbar-dark bg-info">
  <a class="navbar-brand" href="{% url 'ecommerceapp:clienthome' %}">O-shop</a>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
  
        <li class="nav-item active">
        <a class="nav-link" href="{% url 'ecommerceapp:clienthome' %}">Home</a>
      </li>
       <li class="nav-item active">
        <a class="nav-link" href="{% url 'ecommerceapp:cart' %}"><span class="fa fa-shopping-cart"></span></a>
      </li>
      {% if request.user.is_authenticated %}
        <li class="nav-link">Logged in as: <span class="text-dark">{{request.user}}</span></li>
        <li class="nav-item active">
         
          <a class="nav-link" href="{% url 'ecommerceapp:customersignout' %}">Sign out</a>
      </li> 
       <li class="nav-item active">
         
          <a class="nav-link" href="{% url 'ecommerceapp:customerprofile' %}">Profile</a>
      </li> 
        {% else %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'ecommerceapp:customersignin' %}">Sign In</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'ecommerceapp:customersignup' %}">Sign Up</a>
      </li>
      {% endif %}
  
  
    </ul>
    <form class="form-inline my-2 my-lg-0" method="GET" action="">
      <input class="form-control mr-sm-2" type="text" name="ishara"  placeholder="Search....">
      <button class="btn btn-outline-success my-2 my-sm-0">Search</button>
    </form>
  </div>
</nav>
	<div class="row">
		<div class="col-md-3">
			<h3>Categories</h3>
			{% for cat in root_categories %}
			<li>
			<a href="{% url 'ecommerceapp:categorydetail' cat.slug %}">{{cat.title}}</a>
			</li>
			{% for subcat in cat.productcategory_set.all %}
			<li class="ml-5">
			<a href="{% url 'ecommerceapp:categorydetail' subcat.slug %}">{{subcat.title}}</a>
			</li>

			{% endfor %}
			{% endfor %}
		</div>
		<div class="col-md-9">
			{% block content %}
			{% endblock %}


		</div>
	</div>
</body>
</html>

templates/clienttemplate/cart.html
{%  extends "clienttemplate\base.html" %}
{% load static %}

{% block content %}
<h3>My cart</h3>
<a href="{% url 'ecommerceapp:emptycart'  %}" class="btn btn-danger"><span class="fa fa-trash"></span></a>


<table class="table">
<thead>
	<tr>
	<th>S.N</th>
	<th>Product</th>
	<th>Product Image</th>
	<th>Rate</th>
	<th>Quantity</th>
	<th>Action</th>
	<th>Subtotal</th>
	</tr>
</thead>
<tbody>
{% for cartproduct in mycart.cartproduct_set.all %}
<tr>
<td>{{forloop.counter}}</td>
<td>{{cartproduct.product}}</td>
<td><img src="{{cartproduct.product.image.url}}" style="height: 100px;width: 100px"></td>
<td>{{cartproduct.rate}}</td>
<td>{{cartproduct.quantity}}</td>
<td><a href="{% url 'ecommerceapp:managecart' cartproduct.id 'inr' %}" class="btn btn-info"><span class="fa fa-plus"></span></a>
<a href="{% url 'ecommerceapp:managecart' cartproduct.id 'dcr' %}" class="btn btn-info"><span class="fa fa-minus"></span></a>
	<a href="{% url 'ecommerceapp:managecart' cartproduct.id 'rmv' %}" class="btn btn-danger"><span class="fa fa-trash"></span></a>
</td>
<td>{{cartproduct.subtotal}}</td>
	
</tr>	
{% endfor %}
<tr>
	<th colspan="6" class="text-right">Total:</th>
	<th>{{mycart.total}}</th>
</tr>
</tbody>

	
</table>
<a href="{% url 'ecommerceapp:ordercreate'  %}" class="btn btn-info"><span class="fa fa-checkout">Checkout</span></a>



	{% endblock %} 

templates/clienttemplate/categorydetail.html
{%  extends "clienttemplate\base.html" %}
{% load static %}

{% block content %}
<h3 style="text-align: center;color: #17a2b8!important">Category:{{categoryobject.title}}</h3>
<div class="row">
{% for product in categoryobject.product_set.all %}
<div class="col-md-3">
		
<img src="{{product.image.url}}" alt="Avatar" class="image" class="img-fluid" style="height: 200px">
<h5 style="color: #17a2b8!important;text-align: center;">{{product.title}}</h5>
<p style="text-align: center;">Price:<strike>RS.{{product.mrp}}</strike><br>
RS.{{product.sp}}</p>
<div class="overlay">
<a class="text" style="color: #17a2b8!important" href="{% url 'ecommerceapp:addtocart' product.id %}">Add to cart</a>

</div>

</div>
		{% endfor %}
</div>


{% for subcat in categoryobject.productcategory_set.all %}
<h4 class="text-info">{{subcat.title}}</h4>
<hr>
<div class="row">
	{% for product in subcat.product_set.all %}
	<div class="col-md-3">
<img src="{{product.image.url}}" alt="Avatar" class="image" class="img-fluid" style="height: 200px">
<h5 style="color: #17a2b8!important;text-align: center;">{{product.title}}</h5>
<p style="text-align: center;">Price:<strike>RS.{{product.mrp}}</strike><br>
RS.{{product.sp}}</p>
<div class="overlay">
<a class="text"  style="color: #17a2b8!important" href="{% url 'ecommerceapp:addtocart' product.id %}">Add to cart</a>

				

	</div>
	</div>
	{% endfor %}
</div>
{% endfor%}
{% endblock %} 

templates/clienttemplate/customerprofile.html
{%  extends "clienttemplate\base.html" %}
{% load static %}

{% block content %}


{% if request.user.is_authenticated %}
<h1 ><b style="color: #17a2b8!important">{{ request.user }}</b> welcome to your profile </h1>
<hr>
<div class="row">

	<div class="col-md-4">
		<h4><small>Your profile</small></h4>

		<div class="card">
			<img src="{{ request.user.customer.photo.url }}"  alt="Avatar" style="width:100%">



			<div class="contain">
				<h4><b>{{ request.user.customer.name }}</b></h4> 
				<p><small>Username:{{ request.user.customer.name }}</small></p> 
				<p><small>Email:{{ request.user.email }}</small></p> 
				<p><small>Address:{{ request.user.customer.address }}</small></p> 
				<p><small>Contact no:{{ request.user.customer.mobile }}</small></p> 
<span class="fa fa-edit" style="color: red"><a href=""></a></span>
			</div>
		</div>

		{% endif %}
	</div>


	<div class="col-md-8">
		<table class="table table-striped">
			<h3>Your order history</h3>


			<thead>
				<tr>
				<th>Order Date</th>
					<th>Order Product</th> 
					<th>Product image</th>
					<th>Order Qunatity</th>
					<th>Rate</th>
					<th>Order status</th>
					<th>Payment</th>

				</tr>
			</thead>
			<tbody>

{% for order in order.cart.cartproduct_set.all %}
				<tr>
					<td scope="row">{{order.product.title}}</td>
					<td>xxx</td>
					<td>xxx</td>

					<td>xxx</td>
					<td>xxx</td>
					<td>xxx</td>
					<td>xxx</td>

				

				</tr>
{% endfor %}
			</tbody>


		</table>

	</div>
</div>



{% endblock %} 

templates/clienttemplate/customersignin.html
{%  extends "clienttemplate\base.html" %}
{% load static %}

{% block content %}

<div class="row">

	<div class="col-md-4 mx-auto">
	<p>{{error}}</p>
	<h4>Sign In form</h4>
	 <form method="POST" enctype="multipart/form-data" action="">
	{% csrf_token %}
	{{form.as_p}}
	<button class="btn btn-info btn-block">Signin</button>
	
</form>
	</div>
</div>

{% endblock %} 

templates/clienttemplate/customersignup.html
{%  extends "clienttemplate\base.html" %}
{% load static %}

{% block content %}

<div class="row">
	<div class="col-md-4 mx-auto">
	<h4>Sign up form</h4>
	 <form method="POST" enctype="multipart/form-data" action="">
	{% csrf_token %}
	{{form.as_p}}
	<button class="btn btn-info btn-block">Signup</button>
	
</form>
	</div>
</div>

{% endblock %} 

templates/clienttemplate/home.html
{%  extends "clienttemplate\base.html" %}
{% load static %}

{% block content %}

<hr>
<h3 style="text-align: center;color: #17a2b8!important">All products</h3>
<hr>
<div class="row">
{% for product in allproducts %}

<div class="col-md-3">

<img src="{{product.image.url}}" alt="Avatar" class="img-fluid" style="height: 200px">
<h5 style="color: #17a2b8!important;text-align: center;">{{product.title}}</h5>
<p style="text-align: center;">Price:<strike>RS.{{product.mrp}}</strike><br>
RS.{{product.sp}}</p>

<div class="overlay">
<a class="text" style="color: #17a2b8!important" href="{% url 'ecommerceapp:addtocart' product.id %}">Add to cart</a>
</div>

</div>
<br>

{% endfor %}


</div>


{% endblock %} 

templates/clienttemplate/managecart.html
<h4>{{message}}</h4>

templates/clienttemplate/ordercreate.html
{%  extends "clienttemplate\base.html" %}
{% load static %}

{% block content %}
<h3>Order Form</h3>
<hr>
<a href="{% url 'ecommerceapp:cart'  %}" class="btn btn-danger">ManageCart</a>
<div class="row">

<div class="col-md-6">
<table class="table">
	<thead>
		<tr>
			<th>S.N</th>
			<th>Product</th>
			<th>Subtotal</th>
		</tr>
	</thead>

	<tbody>
		{% for cartproduct in cart_obj.cartproduct_set.all %}
		<tr>
		<td>{{forloop.counter}}</td>
		<td>{{cartproduct.product}}</td>
		<td>{{cartproduct.rate}}*{{cartproduct.quantity}}={{cartproduct.subtotal}}</td>
		</tr>
		{% endfor %}
		<tr>
			<th class="text-right" colspan="2">Total</th>
			<th >{{cart_obj.total}}</th>
		</tr>
	</tbody>
</table>
	
</div>
<div class="col-md-6">
	<form method="POST" enctype="multipart/form-data" action="">
	{% csrf_token %}
	{{form.as_p}}
	<button class="btn btn-info btn-block">Place Order</button>
	
</form>
</div>
	
</div>


{% endblock %} 