ecommerceapp/urls.py
from django.urls import path
from .views import *
# from .views import


app_name = "ecommerceapp"

urlpatterns = [
    path('', ClientHomeView.as_view(), name='clienthome'),
    path('category/<slug:slug>', CategoryDetailView.as_view(), name="categorydetail"),
    path('add-to-cart/<int:pk>/', AddToCartView.as_view(), name="addtocart"),
    path('cart/', CartView.as_view(), name="cart"),
    path('manage-cart/<int:pk>/<action>/',
         ManageCartView.as_view(), name="managecart"),
    path('empty-cart/', EmptyCartView.as_view(), name="emptycart"),
    path('customer/sign-up', CustomerSignupView.as_view(), name="customersignup"),
    path('customer/sign-in', CustomerSigninView.as_view(), name="customersignin"),
    path("customer/sign-out", CustomerSignoutView.as_view(), name="customersignout"),
    path("customer/profile", CustomerProfileView.as_view(), name="customerprofile"),
    path('customer/<int:pk>/profile',
         ProfileDetailView.as_view(), name='profiledetail'),

    path('order/', OrderCreateView.as_view(), name="ordercreate"),




    path('med-admin/home/', AdminHomeView.as_view(), name='adminhome'),
    path('med-admin/cartlist', AdminCartListView.as_view(), name='admincartlist'),

    path("med-admin/cartlist/<int:pk>/detail/",
         AdminCartListDetailView.as_view(), name="admincartlistdetail"),
    path('med-admin/orderlist', AdminOrderListView.as_view(), name='adminorderlist'),
    path("med-admin/orderlist/<int:pk>/detail/",
         AdminOrderListDetailView.as_view(), name="adminorderlistdetail"),

    # admin product category
    path('med-admin/productcategory/create',
         AdminProductCategoryCreateView.as_view(), name='adminproductcategorycreate'),
    path('med-admin/productcategory/list',
         AdminProductCategoryListView.as_view(), name='adminproductcategorylist'),
    path('med-admin/productcategory/<int:pk>/delete',
         AdminProductCategoryDeleteView.as_view(), name='adminproductcategorydelete'),
    path('med-admin/productcategory/<int:pk>/update',
         AdminProductCategoryUpdateView.as_view(), name='adminproductcategoryupdate'),

    # admin product
    path('med-admin/product/create',
         AdminProductCreateView.as_view(), name='adminproductcreate'),
    path('med-admin/product/list',
         AdminProductListView.as_view(), name='adminproductlist'),
    path('med-admin/product/<int:pk>/delete',
         AdminProductDeleteView.as_view(), name='adminproductdelete'),
    path('med-admin/product/<int:pk>/update',
         AdminProductUpdateView.as_view(), name='adminproductupdate'),

    # admin product image
    path('med-admin/productimage/create',
         AdminProductImageCreateView.as_view(), name='adminproductimagecreate'),
    path('med-admin/productimage/list',
         AdminProductImageListView.as_view(), name='adminproductimagelist'),
    path('med-admin/productimage/<int:pk>/delete',
         AdminProductImageDeleteView.as_view(), name='adminproductimagedelete'),
    path('med-admin/productimage/<int:pk>/update',
         AdminProductImageUpdateView.as_view(), name='adminproductimageupdate'),




]

ecommerceproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('django-admin/', admin.site.urls),
    path('', include('ecommerceapp.urls')),
   
    

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/admintemplate/admincartlist.html
{% extends 'admintemplate/base.html' %}

{% block content %}
<!-- <h2 class="main-title-w3layouts mb-2 text-center">Tables</h2> -->
            <!--// main-heading -->

            <!-- Tables content -->
                <div class="row">
                	<div class="col-md-10">
                		
		                
                	</div>
                	
                </div>
            <section class="tables-section">
                
                <!-- table5 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">All Cart</h4>

                    <table class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">S.N</th>
                                 <th scope="col">Customer</th>
                                <th scope="col">Cart</th>
                                 <th scope="col">Quantity</th>
                                  <th scope="col">Total</th>
                             
                                <th scope="col">Created at</th>
                                <th scope="col">Updated at</th>
                                <th scope="col">Action</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                        	{% for cart in admincartlist %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{cart.customer.name}}</td>
                                <td>cart-{{cart.id}}</td>
                                <td>{{cart.cartproduct_set.count}}</td>
                                <td>Rs{{cart.total}}</td>
                               
                                <td>{{cart.created_at}}</td>
                                <td>{{cart.updated_at}}</td>

                                <td>
                                    <a href="{% url 'ecommerceapp:admincartlistdetail' cart.pk %}">View Cart Detail</a>
                                </td>
                               
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!--// table5 -->

            </section>

{% endblock %}

templates/admintemplate/admincartlistdetail.html
{% extends 'admintemplate/base.html' %}

{% block content %}

<div class="row">
    <div class="col-md-10">
        
<h3 style="text-align: center;">Cart-no: <small><b>{{cartobject.id}}</small></b></h3><br/>
<table class="table">
<thead>
    <tr>
    <th>S.N</th>
    <th>Product</th>
    <th>Rate</th>
    <th>Quantity</th>
    <th>Created Date</th>
    <th>Subtotal</th>
    </tr>
</thead>
<tbody>
        {% for cart in cartobject.cartproduct_set.all %}

<tr>
<td>{{forloop.counter}}</td>
<td>{{cart.product}}</td>
<td>{{cart.rate}}</td>
<td>{{cart.quantity}}</td>
<td>{{cart.created_at}}</td>
<td>{{cart.subtotal}}</td>
    
</tr>   
{% endfor %}
<tr>
    <th colspan="5" class="text-right">Total:</th>
    <th>{{cartobject.total}}</th>
</tr>
</tbody>

    
</table>
      
    </div>
    
</div>


{% endblock %}

templates/admintemplate/adminorderlist.html
{% extends 'admintemplate/base.html' %}

{% block content %}
<!-- <h2 class="main-title-w3layouts mb-2 text-center">Tables</h2> -->
            <!--// main-heading -->

            <!-- Tables content -->
                <div class="row">
                	<div class="col-md-10">
                		
		                
                	</div>
                	
                </div>
            <section class="tables-section">
                
                <!-- table5 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">All Order</h4>

                    <table class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">S.N</th>
                                <th scope="col">order id</th>
                                <th scope="col">order user</th>
                                <th scope="col">Order Quantity</th>
                                <th scope="col">order status</th>
                                <th scope="col">Order Total</th>
                                 
                                <th scope="col">Action</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                        	{% for order in adminorderlist %}
                            <tr>
                            
                               
                            </tr>
                            <th scope="row">{{forloop.counter}}</th>
                                <td>order-{{order.id}}</td>
                                <td>{{order.cart.customer.name}}</td>
                                <td>{{order.cart.cartproduct_set.count}}</td>
                                <td>{{order.order_status}}</td>
                                <td>Rs.{{order.total}}</td>
                                <td><a href="{% url 'ecommerceapp:adminorderlistdetail' order.pk %}">View</a></td>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
               

            </section>

{% endblock %}

templates/admintemplate/adminorderlistdetail.html
{% extends 'admintemplate/base.html' %}



{% block content %}

<div class="row">
    <div class="col-md-6">
        
<h3 style="text-align: center;">Order-no: <small><b>{{orderobject.id}}</small></b></h3>
<h2>Customer name: <a href="">{{orderobject.cart.customer}}</a></h2><br/>
<table class="table table-bordered table-hover table-striped">
    <thead>
        <tr>
        <th>S.N</th>
        <th>Product</th>
        <th> Image</th>
        <th>Rate</th>
        <th>Quantity</th>
        <th>Subtotal</th>
        </tr>
    </thead>
    <tbody>
        {% for cartproduct in orderobject.cart.cartproduct_set.all %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{cartproduct.product.title}}</td>
            <td><img src="{{cartproduct.product.image.url}}" style="width: 50px;height: 50px"></td>
            <td>{{cartproduct.rate}}</td>
            <td>{{cartproduct.quantity}}</td>
            <td>{{cartproduct.subtotal}}</td>
        </tr>
        {% endfor %}
        <tr>
            <td colspan="5" class="text-right">Subtotal</td>
            <td>{{orderobject.subtotal}}</td>
        </tr>
        <tr>
            <td colspan="5" class="text-right">Discount</td>
            <td>{{orderobject.discount}}</td>
        </tr>
        <tr>
            <td colspan="5" class="text-right">Net Total</td>
            <td>{{orderobject.total}}</td>
        </tr>

    </tbody>

    
</table>
      
    </div>
    <div class="col-md-6">
        <h4>Billing Address</h4>
        <hr>
        <p>Municipality: {{orderobject.municipality}}</p>
        <p>Street address: {{orderobject.street_address}}</p>
        <p>Contact no: {{orderobject.alt_mobile}}</p>
        <p>0rder status: {{orderobject.order_status}}</p>
        <p>payment mode: {{orderobject.payment_mode}}</p>
    </div>
    
</div>




                                

{% endblock %}

templates/admintemplate/adminproductcategorycreate.html
{%  extends "admintemplate\base.html" %}
{% load static %}

{% block content %}

<div class="row">

	<div class="col-md-4 mx-auto">
	<p>{{error}}</p>
	<h4>Product Category Form</h4>
	 <form method="POST" enctype="multipart/form-data" action="">
	{% csrf_token %}
	{{form.as_p}}
	<button class="btn btn-info btn-block">Add Category</button>
	
</form>
	</div>
</div>

	{% endblock %} 

templates/admintemplate/adminproductcategorydelete.html
{% extends 'admintemplate/base.html' %}
{% block content %}
<h3>Product category delete</h3>
<form method="POST">
{% csrf_token %}
<p>Are you sure you want to delete it</p>
<button class="btn btn-danger">yes</button>
<a href="/post/list/" class="btn btn-info">cancel</a>
</form>

{% endblock %}

templates/admintemplate/adminproductcategorylist.html
{% extends 'admintemplate/base.html' %}

{% block content %}
<!-- <h2 class="main-title-w3layouts mb-2 text-center">Tables</h2> -->
            <!--// main-heading -->

            <!-- Tables content -->
                <div class="row">
                	<div class="col-md-10">
                		
		               
                        <a href="{% url 'ecommerceapp:adminproductcategorycreate'  %}" class="btn btn-info"><span class="fa fa-plus"> Product Category</span></a>
                	</div>
                	
                </div>
            <section class="tables-section">
                
                <!-- table5 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">All Product Category</h4>

                    <table class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">S.N</th>
                                <th scope="col">Title</th>
                                <th scope="col">slug</th>
                                <th scope="col">Image</th>
                                <th scope="col">root</th>
                         
                                 
                                <th scope="col">Action</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                        	{% for productcategory in adminproductcategorylist %}
                            <tr>
                            
                               
                            </tr>
                            <th scope="row">{{forloop.counter}}</th>
                                <td>{{productcategory.title}}</td>
                                <td>{{productcategory.slug}}</td>
                                <td><img src="{{productcategory.image.url}}" style="height: 100px;width: 100px">
                                <td>{{productcategory.root}}</td>
                               
                                <td>
                                    <a href="{% url 'ecommerceapp:adminproductcategorydelete' productcategory.id %}"><span class="fa fa-trash"></span></a>
                                    <br/>
                                    <a href="{% url 'ecommerceapp:adminproductcategoryupdate' productcategory.id %}"><span class="fa fa-edit"></span></a>
                                </td>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
               

            </section>

{% endblock %}

templates/admintemplate/adminproductcreate.html
{%  extends "admintemplate\base.html" %}
{% load static %}

{% block content %}

<div class="row">

	<div class="col-md-4 mx-auto">
	<p>{{error}}</p>
	<h4>Product  Form</h4>
	 <form method="POST" enctype="multipart/form-data" action="">
	{% csrf_token %}
	{{form.as_p}}
	<button class="btn btn-info btn-block">Add Product</button>
	
</form>
	</div>
</div>

	{% endblock %} 

templates/admintemplate/adminproductdelete.html
{% extends 'admintemplate/base.html' %}
{% block content %}
<h3>Product delete</h3>
<form method="POST">
{% csrf_token %}
<p>Are you sure you want to delete it</p>
<button class="btn btn-danger">yes</button>
<a href="/post/list/" class="btn btn-info">cancel</a>
</form>

{% endblock %}

templates/admintemplate/adminproductimagecreate.html
{%  extends "admintemplate\base.html" %}
{% load static %}

{% block content %}

<div class="row">

	<div class="col-md-4 mx-auto">
	<p>{{error}}</p>
	<h4>Product Image Form</h4>
	 <form method="POST" enctype="multipart/form-data" action="">
	{% csrf_token %}
	{{form.as_p}}
	<button class="btn btn-info btn-block">Add Image</button>
	
</form>
	</div>
</div>

	{% endblock %} 

templates/admintemplate/adminproductimagedelete.html
{% extends 'admintemplate/base.html' %}
{% block content %}
<h3>Product image delete</h3>
<form method="POST">
{% csrf_token %}
<p>Are you sure you want to delete it</p>
<button class="btn btn-danger">yes</button>
<a href="" class="btn btn-info">cancel</a>
</form>

{% endblock %}

templates/admintemplate/adminproductimagelist.html
{% extends 'admintemplate/base.html' %}

{% block content %}
<!-- <h2 class="main-title-w3layouts mb-2 text-center">Tables</h2> -->
            <!--// main-heading -->

            <!-- Tables content -->
                <div class="row">
                	<div class="col-md-10">
                		
		               
                        <a href="{% url 'ecommerceapp:adminproductimagecreate'  %}" class="btn btn-info"><span class="fa fa-plus"> Product image </span></a>
                	</div>
                	
                </div>
            <section class="tables-section">
                
                <!-- table5 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">All Product image</h4>

                    <table class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">S.N</th>
                                <th scope="col">Product</th>
                                <th scope="col">Image</th>
                                

                         
                                 
                                <th scope="col">Action</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                        	{% for image in adminproductimagelist %}
                            <tr>
                            
                               
                            </tr>
                            <th scope="row">{{forloop.counter}}</th>
                                <td>{{image.product}}</td>
                                <td><img src="{{image.image.url}}" style="height: 150px;width: 150px"></td>
                            


                                
                                                               
                                <td>
                                    <a href="{% url 'ecommerceapp:adminproductimagedelete' image.id %}"><span class="fa fa-trash"></span></a>
                                    <br/>
                                    <a href="{% url 'ecommerceapp:adminproductimageupdate' image.id %}"><span class="fa fa-edit"></span></a>
                                </td>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
               

            </section>

{% endblock %}

templates/admintemplate/home.html
{%  extends "admintemplate\base.html" %}
{% load static %}

{% block content %}



	{% endblock %} 